name: Send Emails - EV Marketing Campaign - Batch 2 Placement (Feb 2026)
on:
  # schedule:
  #   - cron: "0 9 * * *" 
  workflow_dispatch: 

jobs:
  send-email-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 

      matrix:
        job_config:
          # - '{"account_index": 0, "limit": 3000, "tables": ["test"], "mod_total": 2, "mod_value": 0}'
          # - '{"account_index": 1, "limit": 3000, "tables": ["test"], "mod_total": 2, "mod_value": 1}'
          # - '{"account_index": 0, "limit": 3000, "tables": ["crdf25", "crdf25_north", "crdf25_south"], "mod_total": 2, "mod_value": 0}'
          # - '{"account_index": 1, "limit": 3000, "tables": ["crdf25", "crdf25_north", "crdf25_south"], "mod_total": 2, "mod_value": 1}'
          - '{"account_index": 0, "limit": 2000, "tables": ["email_list_1", "email_list_2", "email_list_3", "email_list_4", "email_list_5", "email_list_6", "email_list_7"], "mod_total": 2, "mod_value": 0}'
          - '{"account_index": 1, "limit": 2000, "tables": ["email_list_1", "email_list_2", "email_list_3", "email_list_4", "email_list_5", "email_list_6", "email_list_7"], "mod_total": 2, "mod_value": 1}'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Fallback installation if requirements.txt is missing but needed for the script
          pip install mysql-connector-python

      - name: Run the Python script for Job (Mod ${{ fromJson(matrix.job_config).mod_value }})
        run: python email-campaign-8-script-smtp.py --config '${{ matrix.job_config }}'