name: Send Internship Offers

on:
  workflow_dispatch:

jobs:
  send-offer-letters:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas PyMuPDF reportlab

      - name: Run offer letter script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python "VTU EV Internship Offer Letters/ev-internship-offer-letters.py"

      - name: Commit updated CSV file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          git add 'VTU EV Internship Offer Letters/jan_offer_released_applicants_4.csv'
          # Check if there are any changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update email sent status in applicants list"
            git push
          fi
